---
# Server configuration
timezone: America/Lima

# Package version
php_version: 8.1
mysql_version: 8.0

# Git configuration
git_repository: git@bitbucket.org:telefonica-peru/dev-ecommerce-tdp-bkp.git
git_branch: magento24
ssh_rsa_key: /home/magento/.ssh/id_rsa

# Magento
magento_dir: /home/magento/Sites/telefonica

# Database configuration
db_host: localhost
db_name: magento
db_user: admin
db_password: admin

# Elasticsearch configuration
elasticsearch_version: "7.x"
elasticsearch_network_host: localhost
elasticsearch_http_port: 9200
elasticsearch_heap_size_min: 1g
elasticsearch_heap_size_max: 2g
