---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Add Nginx Configuration File
  template:
    src: magento.j2
    dest: "/etc/nginx/sites-available/{{ server_hostname }}"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify:
    - Reload Nginx Configuration

- name: Create Symbolic Link
  file:
    src: "/etc/nginx/sites-available/{{ server_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ server_hostname }}"
    owner: root
    group: root
    state: link
  notify:
    - Reload Nginx Configuration

- name: Start Nginx Service
  command: sudo service nginx start
