---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - common
    - git
    - php
    - mysql
    - composer
    - magento
    - nginx
    - elasticsearch
    - phpmyadmin
    - nginx_default
    - utils
  tasks:
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
        autoremove: yes

- hosts: telefonica
  become: true
  become_method: sudo
  roles:
    - website

- hosts: telefonica-mb
  become: true
  become_method: sudo
  roles:
    - website
