---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - common
    - git
    - php
    - mysql
    - composer
    - magento
    - nginx
    - elasticsearch
    - phpmyadmin
    - nginx_default

- hosts: telefonica
  become: true
  become_method: sudo
  roles:
    - nginx

- hosts: telefonica-mb
  become: true
  become_method: sudo
  roles:
    - nginx
