---
- name: Update Repository and Full-Upgrade Packages
  become: true
  become_method: sudo
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: Set Server Timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Create a directory if it does not exist
  become_user: magento
  file:
    path: /home/magento/Sites
    state: directory
    mode: "0755"
