---
- name: Add PHP Repository from PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    codename: focal

- name: Install PHP {{ php_version }} and Magento PHP Dependencies
  become: true
  become_method: sudo
  apt:
    name:
      [
        "php{{ php_version }}",
        "php{{ php_version }}-fpm",
        "php{{ php_version }}-bcmath",
        "php{{ php_version }}-cli",
        "php{{ php_version }}-curl",
        "php{{ php_version }}-dom",
        "php{{ php_version }}-gd",
        "php{{ php_version }}-iconv",
        "php{{ php_version }}-intl",
        "php{{ php_version }}-mbstring",
        "php{{ php_version }}-mysql",
        "php{{ php_version }}-simplexml",
        "php{{ php_version }}-soap",
        "php{{ php_version }}-opcache",
        "php{{ php_version }}-xsl",
        "php{{ php_version }}-zip",
      ]
    state: latest

- name: Start PHP {{ php_version }} Service
  command: sudo service php{{ php_version }}-fpm start
